import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import path from 'path';

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      '@': path.resolve(__dirname, './src'),
    },
  },
  build: {
    rollupOptions: {
      output: {
        manualChunks: {
          vendor: ['react', 'react-dom', 'react-router-dom'],
          ui: ['framer-motion', '@tanstack/react-query', 'zustand', 'axios', 'lucide-react'],
        },
      },
    },
  },
  server: {
    port: 5173,
    proxy: {
      '/api/v1/auth': 'http://localhost:8001',
      '/api/v1/users': 'http://localhost:8001',
      '/api/v1/setup': 'http://localhost:8001',
      '/api/v1/equipment': 'http://localhost:8002',
      '/api/v1/categories': 'http://localhost:8002',
      '/api/v1/equipment-types': 'http://localhost:8002',
      '/api/v1/flightcases': 'http://localhost:8002',
      '/api/v1/projects': 'http://localhost:8003',
      '/api/v1/packlists': 'http://localhost:8003',
      '/api/v1/reservations': 'http://localhost:8003',
      '/api/v1/scanner': 'http://localhost:8004',
      '/api/v1/warehouses': 'http://localhost:8005',
      '/api/v1/zones': 'http://localhost:8005',
      '/api/v1/racks': 'http://localhost:8005',
      '/api/v1/locations': 'http://localhost:8005',
      '/api/v1/movements': 'http://localhost:8005',
      '/api/v1/inventory-checks': 'http://localhost:8005',
      '/api/v1/invoices': 'http://localhost:8006',
      '/api/v1/document-templates': 'http://localhost:8007',
      '/api/v1/documents': 'http://localhost:8007',
      '/api/v1/attachments': 'http://localhost:8007',
      '/api/v1/crew': 'http://localhost:8008',
      '/api/v1/crew-assignments': 'http://localhost:8008',
      '/api/v1/report-definitions': 'http://localhost:8016',
      '/api/v1/report-snapshots': 'http://localhost:8016',
      '/api/v1/dashboard-widgets': 'http://localhost:8016',
      '/api/v1/expense-categories': 'http://localhost:8018',
      '/api/v1/expenses': 'http://localhost:8018',
      '/api/v1/federation-partners': 'http://localhost:8009',
      '/api/v1/shared-listings': 'http://localhost:8009',
      '/api/v1/federation-requests': 'http://localhost:8009',
      '/api/v1/maintenance-schedules': 'http://localhost:8010',
      '/api/v1/maintenance-tasks': 'http://localhost:8010',
      '/api/v1/vehicles': 'http://localhost:8011',
      '/api/v1/transport-orders': 'http://localhost:8011',
      '/api/v1/insurance-policies': 'http://localhost:8012',
      '/api/v1/insurance-claims': 'http://localhost:8012',
      '/api/v1/workflow-definitions': 'http://localhost:8013',
      '/api/v1/workflow-instances': 'http://localhost:8013',
      '/api/v1/ai-predictions': 'http://localhost:8014',
      '/api/v1/ai-suggestions': 'http://localhost:8014',
      '/api/v1/ai-training-data': 'http://localhost:8014',
      '/api/v1/notifications': 'http://localhost:8015',
      '/api/v1/notification-preferences': 'http://localhost:8015',
      '/api/v1/audit-logs': 'http://localhost:8017',
      '/api/v1/audit-policies': 'http://localhost:8017',
      '/api/v1/customers': 'http://localhost:8019',
      '/api/v1/contacts': 'http://localhost:8019',
    },
  },
});
