// ============================================================================
// Industry Profile Definitions
// ============================================================================

export interface IndustryProfile {
  id: string
  label: string
  group: string
  labels: Record<string, string>
  features: Record<string, boolean>
  scannerHomeCards: string[]
  categories: string[]
}

export interface IndustryGroup {
  id: string
  label: string
  icon: string // lucide icon name
  profiles: string[] // profile IDs
}

// Groups for the setup wizard / settings UI
export const INDUSTRY_GROUPS: IndustryGroup[] = [
  {
    id: 'technik',
    label: 'Technik',
    icon: 'Monitor',
    profiles: ['event_tech', 'film_tech', 'it_rental'],
  },
  {
    id: 'maschinen',
    label: 'Maschinen & Werkzeuge',
    icon: 'Wrench',
    profiles: ['construction', 'tool_rental', 'scaffolding', 'landscaping', 'electrical'],
  },
  {
    id: 'ausstattung',
    label: 'Ausstattung & Mobiliar',
    icon: 'Sofa',
    profiles: ['party_rental', 'exhibition', 'gastro', 'textile', 'staging'],
  },
  {
    id: 'fahrzeuge',
    label: 'Fahrzeuge & Outdoor',
    icon: 'Truck',
    profiles: ['vehicle_rental', 'camping', 'sports'],
  },
  {
    id: 'sonstiges',
    label: 'Sonstiges',
    icon: 'Package',
    profiles: ['container', 'medical', 'general'],
  },
]

// Default labels (fallback)
export const DEFAULT_LABELS: Record<string, string> = {
  project: 'Projekt',
  checkout: 'Ausgabe',
  checkin: 'Rueckgabe',
  location: 'Lager',
  crew: 'Crew',
  worker: 'Mitarbeiter',
}

// All industry profiles
export const INDUSTRY_PROFILES: Record<string, IndustryProfile> = {
  event_tech: {
    id: 'event_tech',
    label: 'Veranstaltungstechnik',
    group: 'Technik',
    labels: {
      project: 'Veranstaltung',
      checkout: 'Ausgabe',
      checkin: 'Rueckgabe',
      location: 'Lager',
      crew: 'Crew',
      worker: 'Techniker',
    },
    features: {
      packing_lists: true,
      operating_hours: false,
      fuel_tracking: false,
      cleaning_status: false,
      crew_planning: true,
      flight_cases: true,
      cable_tracking: true,
      power_distro: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'packing_list', 'inventory'],
    categories: ['Licht', 'Ton', 'Video', 'Rigging', 'Strom', 'Buehne', 'Kabel', 'Zubehoer'],
  },
  film_tech: {
    id: 'film_tech',
    label: 'Film & TV',
    group: 'Technik',
    labels: {
      project: 'Produktion',
      checkout: 'Ausgabe',
      checkin: 'Rueckgabe',
      location: 'Fundus',
      crew: 'Team',
      worker: 'Techniker',
    },
    features: {
      packing_lists: true,
      operating_hours: false,
      fuel_tracking: false,
      cleaning_status: false,
      crew_planning: true,
      flight_cases: true,
      cable_tracking: true,
      serial_tracking: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'packing_list', 'inventory'],
    categories: ['Kamera', 'Objektive', 'Licht', 'Ton', 'Grip', 'Strom', 'Kabel', 'Zubehoer'],
  },
  it_rental: {
    id: 'it_rental',
    label: 'IT & Buerotechnik',
    group: 'Technik',
    labels: {
      project: 'Auftrag',
      checkout: 'Ausgabe',
      checkin: 'Rueckgabe',
      location: 'Lager',
      crew: 'Team',
      worker: 'Techniker',
    },
    features: {
      packing_lists: true,
      operating_hours: false,
      fuel_tracking: false,
      cleaning_status: false,
      serial_tracking: true,
      asset_tags: true,
      software_config: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'inventory'],
    categories: ['Laptops', 'Monitore', 'Drucker', 'Netzwerk', 'Server', 'Zubehoer', 'Kabel', 'Moebel'],
  },
  construction: {
    id: 'construction',
    label: 'Baumaschinen',
    group: 'Maschinen & Werkzeuge',
    labels: {
      project: 'Baustelle',
      checkout: 'Lieferung',
      checkin: 'Abholung',
      location: 'Depot',
      crew: 'Kolonne',
      worker: 'Maschinist',
    },
    features: {
      packing_lists: false,
      operating_hours: true,
      fuel_tracking: true,
      cleaning_status: true,
      damage_report: true,
      maintenance: true,
      weight_tracking: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'damage_report', 'operating_hours'],
    categories: ['Bagger', 'Radlader', 'Krane', 'Verdichter', 'Generatoren', 'Anhaenger', 'Kleingeraete', 'Zubehoer'],
  },
  tool_rental: {
    id: 'tool_rental',
    label: 'Werkzeugverleih',
    group: 'Maschinen & Werkzeuge',
    labels: {
      project: 'Auftrag',
      checkout: 'Ausgabe',
      checkin: 'Rueckgabe',
      location: 'Lager',
      crew: 'Team',
      worker: 'Mitarbeiter',
    },
    features: {
      packing_lists: false,
      operating_hours: true,
      fuel_tracking: false,
      cleaning_status: true,
      maintenance: true,
      calibration: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'inventory'],
    categories: ['Bohrmaschinen', 'Saegen', 'Schleifer', 'Messgeraete', 'Elektrowerkzeug', 'Handwerkzeug', 'Zubehoer'],
  },
  scaffolding: {
    id: 'scaffolding',
    label: 'Geruestbau',
    group: 'Maschinen & Werkzeuge',
    labels: {
      project: 'Baustelle',
      checkout: 'Lieferung',
      checkin: 'Abholung',
      location: 'Lager',
      crew: 'Kolonne',
      worker: 'Geruestbauer',
    },
    features: {
      packing_lists: false,
      operating_hours: false,
      fuel_tracking: false,
      cleaning_status: false,
      piece_counting: true,
      weight_tracking: true,
      safety_inspection: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'inventory', 'piece_count'],
    categories: ['Rahmen', 'Riegel', 'Diagonalen', 'Boeden', 'Kupplungen', 'Konsolen', 'Treppen', 'Zubehoer'],
  },
  landscaping: {
    id: 'landscaping',
    label: 'Landschaftsbau',
    group: 'Maschinen & Werkzeuge',
    labels: {
      project: 'Baustelle',
      checkout: 'Ausgabe',
      checkin: 'Rueckgabe',
      location: 'Lager',
      crew: 'Kolonne',
      worker: 'Gaertner',
    },
    features: {
      packing_lists: false,
      operating_hours: true,
      fuel_tracking: true,
      cleaning_status: true,
      maintenance: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'operating_hours'],
    categories: ['Maeher', 'Heckenscheren', 'Motorsaegen', 'Haecksler', 'Pumpen', 'Anhaenger', 'Handgeraete', 'Zubehoer'],
  },
  electrical: {
    id: 'electrical',
    label: 'Elektrotechnik',
    group: 'Maschinen & Werkzeuge',
    labels: {
      project: 'Baustelle',
      checkout: 'Ausgabe',
      checkin: 'Rueckgabe',
      location: 'Lager',
      crew: 'Team',
      worker: 'Elektriker',
    },
    features: {
      packing_lists: true,
      operating_hours: false,
      fuel_tracking: false,
      cleaning_status: false,
      calibration: true,
      safety_inspection: true,
      cable_tracking: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'inventory'],
    categories: ['Messgeraete', 'Werkzeuge', 'Kabel', 'Verteiler', 'Steckverbinder', 'Sicherheitstechnik', 'Zubehoer'],
  },
  party_rental: {
    id: 'party_rental',
    label: 'Party & Eventausstattung',
    group: 'Ausstattung & Mobiliar',
    labels: {
      project: 'Event',
      checkout: 'Lieferung',
      checkin: 'Abholung',
      location: 'Lager',
      crew: 'Team',
      worker: 'Mitarbeiter',
    },
    features: {
      packing_lists: true,
      operating_hours: false,
      fuel_tracking: false,
      cleaning_status: true,
      piece_counting: true,
      damage_report: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'packing_list', 'piece_count'],
    categories: ['Tische', 'Stuehle', 'Zelte', 'Geschirr', 'Besteck', 'Dekoration', 'Textilien', 'Zubehoer'],
  },
  exhibition: {
    id: 'exhibition',
    label: 'Messebau',
    group: 'Ausstattung & Mobiliar',
    labels: {
      project: 'Messe',
      checkout: 'Lieferung',
      checkin: 'Abholung',
      location: 'Lager',
      crew: 'Team',
      worker: 'Monteur',
    },
    features: {
      packing_lists: true,
      operating_hours: false,
      fuel_tracking: false,
      cleaning_status: true,
      modular_systems: true,
      floor_plans: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'packing_list', 'inventory'],
    categories: ['Waende', 'Boeden', 'Tresen', 'Vitrinen', 'Beleuchtung', 'Grafik', 'Elektrik', 'Zubehoer'],
  },
  gastro: {
    id: 'gastro',
    label: 'Gastro-Equipment',
    group: 'Ausstattung & Mobiliar',
    labels: {
      project: 'Event',
      checkout: 'Lieferung',
      checkin: 'Abholung',
      location: 'Lager',
      crew: 'Team',
      worker: 'Mitarbeiter',
    },
    features: {
      packing_lists: false,
      operating_hours: false,
      fuel_tracking: false,
      cleaning_status: true,
      piece_counting: true,
      hygiene_tracking: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'piece_count'],
    categories: ['Kuehlgeraete', 'Kochgeraete', 'Spuelmaschinen', 'Warmhaltung', 'Zapfanlagen', 'Geschirr', 'Moebel', 'Zubehoer'],
  },
  textile: {
    id: 'textile',
    label: 'Textil & Kostuem',
    group: 'Ausstattung & Mobiliar',
    labels: {
      project: 'Produktion',
      checkout: 'Ausgabe',
      checkin: 'Rueckgabe',
      location: 'Fundus',
      crew: 'Team',
      worker: 'Mitarbeiter',
    },
    features: {
      packing_lists: true,
      operating_hours: false,
      fuel_tracking: false,
      cleaning_status: true,
      size_tracking: true,
      condition_notes: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'inventory'],
    categories: ['Kostueme', 'Anzuege', 'Kleider', 'Schuhe', 'Accessoires', 'Stoffe', 'Requisiten', 'Zubehoer'],
  },
  staging: {
    id: 'staging',
    label: 'Buehnen & Tribuenen',
    group: 'Ausstattung & Mobiliar',
    labels: {
      project: 'Veranstaltung',
      checkout: 'Lieferung',
      checkin: 'Abholung',
      location: 'Lager',
      crew: 'Kolonne',
      worker: 'Monteur',
    },
    features: {
      packing_lists: false,
      operating_hours: false,
      fuel_tracking: false,
      cleaning_status: false,
      piece_counting: true,
      weight_tracking: true,
      safety_inspection: true,
      static_calc: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'inventory', 'piece_count'],
    categories: ['Buehnenelemente', 'Tribuenen', 'Podeste', 'Treppen', 'Gelaender', 'Verkleidungen', 'Daecher', 'Zubehoer'],
  },
  vehicle_rental: {
    id: 'vehicle_rental',
    label: 'Fahrzeugvermietung',
    group: 'Fahrzeuge & Outdoor',
    labels: {
      project: 'Buchung',
      checkout: 'Uebergabe',
      checkin: 'Ruecknahme',
      location: 'Standort',
      crew: 'Team',
      worker: 'Mitarbeiter',
    },
    features: {
      packing_lists: false,
      operating_hours: true,
      fuel_tracking: true,
      cleaning_status: true,
      damage_report: true,
      mileage_tracking: true,
      insurance: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'damage_report', 'operating_hours'],
    categories: ['PKW', 'Transporter', 'LKW', 'Anhaenger', 'Spezialfahrzeuge', 'E-Fahrzeuge', 'Zubehoer'],
  },
  camping: {
    id: 'camping',
    label: 'Camping & Wohnmobile',
    group: 'Fahrzeuge & Outdoor',
    labels: {
      project: 'Buchung',
      checkout: 'Uebergabe',
      checkin: 'Ruecknahme',
      location: 'Standort',
      crew: 'Team',
      worker: 'Mitarbeiter',
    },
    features: {
      packing_lists: false,
      operating_hours: true,
      fuel_tracking: true,
      cleaning_status: true,
      damage_report: true,
      mileage_tracking: true,
      inventory_check: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'damage_report', 'inventory'],
    categories: ['Wohnmobile', 'Wohnwagen', 'Dachzelte', 'Campingmoebel', 'Kochausruestung', 'Outdoor', 'Zubehoer'],
  },
  sports: {
    id: 'sports',
    label: 'Sport & Freizeit',
    group: 'Fahrzeuge & Outdoor',
    labels: {
      project: 'Buchung',
      checkout: 'Ausgabe',
      checkin: 'Rueckgabe',
      location: 'Lager',
      crew: 'Team',
      worker: 'Mitarbeiter',
    },
    features: {
      packing_lists: false,
      operating_hours: false,
      fuel_tracking: false,
      cleaning_status: true,
      size_tracking: true,
      damage_report: true,
      maintenance: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'inventory'],
    categories: ['Ski', 'Snowboard', 'Fahrraeder', 'Boote', 'Surfbretter', 'Klettern', 'Fitness', 'Zubehoer'],
  },
  container: {
    id: 'container',
    label: 'Container & Raumsysteme',
    group: 'Sonstiges',
    labels: {
      project: 'Baustelle',
      checkout: 'Lieferung',
      checkin: 'Abholung',
      location: 'Depot',
      crew: 'Team',
      worker: 'Fahrer',
    },
    features: {
      packing_lists: false,
      operating_hours: false,
      fuel_tracking: false,
      cleaning_status: true,
      damage_report: true,
      location_tracking: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'damage_report'],
    categories: ['Buerocontainer', 'Lagercontainer', 'Sanitaercontainer', 'Wohncontainer', 'Spezialcontainer', 'Zubehoer'],
  },
  medical: {
    id: 'medical',
    label: 'Medizintechnik',
    group: 'Sonstiges',
    labels: {
      project: 'Einsatz',
      checkout: 'Ausgabe',
      checkin: 'Rueckgabe',
      location: 'Lager',
      crew: 'Team',
      worker: 'Techniker',
    },
    features: {
      packing_lists: true,
      operating_hours: false,
      fuel_tracking: false,
      cleaning_status: true,
      serial_tracking: true,
      calibration: true,
      hygiene_tracking: true,
      safety_inspection: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'inventory'],
    categories: ['Diagnostik', 'Therapie', 'Monitoring', 'Beatmung', 'Chirurgie', 'Labor', 'Mobilitaet', 'Zubehoer'],
  },
  general: {
    id: 'general',
    label: 'Allgemeiner Verleih',
    group: 'Sonstiges',
    labels: {
      project: 'Auftrag',
      checkout: 'Ausgabe',
      checkin: 'Rueckgabe',
      location: 'Lager',
      crew: 'Team',
      worker: 'Mitarbeiter',
    },
    features: {
      packing_lists: true,
      operating_hours: false,
      fuel_tracking: false,
      cleaning_status: true,
    },
    scannerHomeCards: ['quick_scan', 'checkout', 'checkin', 'inventory'],
    categories: ['Kategorie 1', 'Kategorie 2', 'Kategorie 3', 'Zubehoer'],
  },
}

// Get a flat list of all profiles
export function getAllProfiles(): IndustryProfile[] {
  return Object.values(INDUSTRY_PROFILES)
}

// Get profiles by group
export function getProfilesByGroup(groupLabel: string): IndustryProfile[] {
  return Object.values(INDUSTRY_PROFILES).filter((p) => p.group === groupLabel)
}
