import { useState, useEffect, useMemo } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import { useQuery, useMutation } from '@tanstack/react-query'
import { invoiceApi } from '../../services/api'
import { Input } from '../../components/Form/Input'
import { TextArea } from '../../components/Form/TextArea'
import { Select } from '../../components/Form/Select'
import { CreateInvoiceDTO } from '../../types/invoice'
import '../Equipment/Equipment.module.scss'

interface LineItem {
  name: string
  description: string
  quantity: number
  unit_price: number
  tax_rate: number
}

const EMPTY_LINE_ITEM: LineItem = {
  name: '',
  description: '',
  quantity: 1,
  unit_price: 0,
  tax_rate: 19,
}

const PAYMENT_TERMS_OPTIONS = [
  { value: '7', label: '7 Tage' },
  { value: '14', label: '14 Tage' },
  { value: '30', label: '30 Tage' },
  { value: '60', label: '60 Tage' },
  { value: 'custom', label: 'Benutzerdefiniert' },
]

function InvoiceFormPage() {
  const navigate = useNavigate()
  const { id } = useParams<{ id: string }>()
  const isEditing = !!id

  const [clientName, setClientName] = useState('')
  const [clientEmail, setClientEmail] = useState('')
  const [clientAddress, setClientAddress] = useState('')
  const [dueDate, setDueDate] = useState('')
  const [notes, setNotes] = useState('')
  const [paymentTerms, setPaymentTerms] = useState('30')
  const [lineItems, setLineItems] = useState<LineItem[]>([{ ...EMPTY_LINE_ITEM }])
  const [errors, setErrors] = useState<Record<string, string>>({})

  const { data: invoice, isLoading: isLoadingInvoice } = useQuery({
    queryKey: ['invoice', id],
    queryFn: () => invoiceApi.getById(id!),
    enabled: isEditing,
  })

  useEffect(() => {
    if (invoice && isEditing) {
      setClientName(invoice.client_name || '')
      setDueDate(invoice.due_date ? invoice.due_date.split('T')[0] : '')
      setNotes(invoice.notes || '')
      if (invoice.line_items && invoice.line_items.length > 0) {
        setLineItems(
          // eslint-disable-next-line @typescript-eslint/no-explicit-any
          invoice.line_items.map((item: any) => ({
            name: item.name || item.description || '',
            description: item.description || '',
            quantity: item.quantity || 1,
            unit_price: item.unit_price || 0,
            tax_rate: item.tax_rate ?? 19,
          }))
        )
      }
    }
  }, [invoice, isEditing])

  const { mutate: saveInvoice, isPending } = useMutation({
    mutationFn: async () => {
      const payload: CreateInvoiceDTO = {
        number: '', // auto-generated by backend
        client_id: '', // will be resolved by backend from client_name
        issue_date: new Date().toISOString().split('T')[0],
        due_date: dueDate,
        notes,
        line_items: lineItems.map((item) => ({
          description: item.name + (item.description ? ` - ${item.description}` : ''),
          quantity: item.quantity,
          unit_price: item.unit_price,
          tax_rate: item.tax_rate,
        })),
      }

      // Include client info as extra fields for the API
      const data = {
        ...payload,
        client_name: clientName,
        client_email: clientEmail,
        client_address: clientAddress,
        payment_terms: paymentTerms,
      }

      if (isEditing && id) {
        return invoiceApi.update(id, data)
      }
      return invoiceApi.create(data)
    },
    onSuccess: () => {
      navigate('/invoices')
    },
    onError: (error: unknown) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const errorMessage =
        (error as any)?.response?.data?.error ||
        (error as any)?.response?.data?.message ||
        'Fehler beim Speichern der Rechnung'
      setErrors({ submit: errorMessage })
    },
  })

  const { subtotal, taxTotal, total } = useMemo(() => {
    let sub = 0
    let tax = 0
    for (const item of lineItems) {
      const lineTotal = item.quantity * item.unit_price
      const lineTax = lineTotal * (item.tax_rate / 100)
      sub += lineTotal
      tax += lineTax
    }
    return { subtotal: sub, taxTotal: tax, total: sub + tax }
  }, [lineItems])

  const validateForm = () => {
    const newErrors: Record<string, string> = {}

    if (!clientName.trim()) {
      newErrors.clientName = 'Kundenname ist erforderlich'
    }
    if (!dueDate) {
      newErrors.dueDate = 'Fälligkeitsdatum ist erforderlich'
    }
    if (lineItems.length === 0) {
      newErrors.lineItems = 'Mindestens eine Position ist erforderlich'
    }
    const hasEmptyItem = lineItems.some(
      (item) => !item.name.trim() || item.quantity <= 0 || item.unit_price <= 0
    )
    if (hasEmptyItem) {
      newErrors.lineItems = 'Alle Positionen müssen Name, Menge und Einzelpreis haben'
    }

    setErrors(newErrors)
    return Object.keys(newErrors).length === 0
  }

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault()
    if (validateForm()) {
      saveInvoice()
    }
  }

  const updateLineItem = (index: number, field: keyof LineItem, value: string | number) => {
    setLineItems((prev) => {
      const updated = [...prev]
      updated[index] = { ...updated[index], [field]: value }
      return updated
    })
    if (errors.lineItems) {
      setErrors((prev) => {
        const updated = { ...prev }
        delete updated.lineItems
        return updated
      })
    }
  }

  const addLineItem = () => {
    setLineItems((prev) => [...prev, { ...EMPTY_LINE_ITEM }])
  }

  const removeLineItem = (index: number) => {
    if (lineItems.length <= 1) return
    setLineItems((prev) => prev.filter((_, i) => i !== index))
  }

  const clearFieldError = (field: string) => {
    if (errors[field]) {
      setErrors((prev) => {
        const updated = { ...prev }
        delete updated[field]
        return updated
      })
    }
  }

  if (isLoadingInvoice) {
    return <div className="invoice-form-page">Wird geladen...</div>
  }

  return (
    <div className="invoice-form-page">
      <div className="page-header">
        <div>
          <h1 className="page-title">
            {isEditing ? 'Rechnung bearbeiten' : 'Neue Rechnung'}
          </h1>
        </div>
      </div>

      <form onSubmit={handleSubmit} className="form-section">
        {errors.submit && (
          <div className="error-message" role="alert">
            {errors.submit}
          </div>
        )}

        <h2 className="form-section__title">Kundeninformationen</h2>
        <div className="form-section__grid">
          <Input
            label="Kundenname *"
            value={clientName}
            onChange={(e) => {
              setClientName(e.target.value)
              clearFieldError('clientName')
            }}
            placeholder="z.B. Musterfirma GmbH"
            error={errors.clientName}
          />
          <Input
            label="E-Mail"
            type="email"
            value={clientEmail}
            onChange={(e) => setClientEmail(e.target.value)}
            placeholder="z.B. kontakt@musterfirma.de"
          />
        </div>
        <TextArea
          label="Adresse"
          value={clientAddress}
          onChange={(e) => setClientAddress(e.target.value)}
          placeholder="Straße, PLZ, Ort"
          rows={3}
        />

        <h2 className="form-section__title">Rechnungsdetails</h2>
        <div className="form-section__grid">
          <Input
            label="Fälligkeitsdatum *"
            type="date"
            value={dueDate}
            onChange={(e) => {
              setDueDate(e.target.value)
              clearFieldError('dueDate')
            }}
            error={errors.dueDate}
          />
          <Select
            label="Zahlungsbedingungen"
            options={PAYMENT_TERMS_OPTIONS}
            value={paymentTerms}
            onChange={(e) => setPaymentTerms(e.target.value)}
          />
        </div>
        <TextArea
          label="Anmerkungen"
          value={notes}
          onChange={(e) => setNotes(e.target.value)}
          placeholder="Optionale Anmerkungen zur Rechnung..."
          rows={3}
        />

        <h2 className="form-section__title">Positionen</h2>
        {errors.lineItems && (
          <div className="error-message" role="alert" style={{ marginBottom: 'var(--spacing-4)' }}>
            {errors.lineItems}
          </div>
        )}

        <div style={{ overflowX: 'auto' }}>
          <table style={{ width: '100%', borderCollapse: 'collapse', marginBottom: 'var(--spacing-4)' }}>
            <thead>
              <tr style={{ borderBottom: '2px solid var(--color-border)' }}>
                <th style={{ textAlign: 'left', padding: 'var(--spacing-2) var(--spacing-3)', minWidth: '160px' }}>
                  Bezeichnung *
                </th>
                <th style={{ textAlign: 'left', padding: 'var(--spacing-2) var(--spacing-3)', minWidth: '140px' }}>
                  Beschreibung
                </th>
                <th style={{ textAlign: 'right', padding: 'var(--spacing-2) var(--spacing-3)', minWidth: '80px' }}>
                  Menge *
                </th>
                <th style={{ textAlign: 'right', padding: 'var(--spacing-2) var(--spacing-3)', minWidth: '100px' }}>
                  Einzelpreis *
                </th>
                <th style={{ textAlign: 'right', padding: 'var(--spacing-2) var(--spacing-3)', minWidth: '80px' }}>
                  MwSt. %
                </th>
                <th style={{ textAlign: 'right', padding: 'var(--spacing-2) var(--spacing-3)', minWidth: '100px' }}>
                  Gesamt
                </th>
                <th style={{ padding: 'var(--spacing-2) var(--spacing-3)', width: '50px' }}></th>
              </tr>
            </thead>
            <tbody>
              {lineItems.map((item, index) => {
                const lineTotal = item.quantity * item.unit_price
                return (
                  <tr key={index} style={{ borderBottom: '1px solid var(--color-border)' }}>
                    <td style={{ padding: 'var(--spacing-2) var(--spacing-3)' }}>
                      <input
                        className="form-input"
                        value={item.name}
                        onChange={(e) => updateLineItem(index, 'name', e.target.value)}
                        placeholder="Bezeichnung"
                      />
                    </td>
                    <td style={{ padding: 'var(--spacing-2) var(--spacing-3)' }}>
                      <input
                        className="form-input"
                        value={item.description}
                        onChange={(e) => updateLineItem(index, 'description', e.target.value)}
                        placeholder="Beschreibung"
                      />
                    </td>
                    <td style={{ padding: 'var(--spacing-2) var(--spacing-3)' }}>
                      <input
                        className="form-input"
                        type="number"
                        value={item.quantity}
                        onChange={(e) => updateLineItem(index, 'quantity', parseFloat(e.target.value) || 0)}
                        min="0"
                        step="1"
                        style={{ textAlign: 'right' }}
                      />
                    </td>
                    <td style={{ padding: 'var(--spacing-2) var(--spacing-3)' }}>
                      <input
                        className="form-input"
                        type="number"
                        value={item.unit_price}
                        onChange={(e) => updateLineItem(index, 'unit_price', parseFloat(e.target.value) || 0)}
                        min="0"
                        step="0.01"
                        style={{ textAlign: 'right' }}
                      />
                    </td>
                    <td style={{ padding: 'var(--spacing-2) var(--spacing-3)' }}>
                      <input
                        className="form-input"
                        type="number"
                        value={item.tax_rate}
                        onChange={(e) => updateLineItem(index, 'tax_rate', parseFloat(e.target.value) || 0)}
                        min="0"
                        step="1"
                        style={{ textAlign: 'right' }}
                      />
                    </td>
                    <td style={{ textAlign: 'right', padding: 'var(--spacing-2) var(--spacing-3)', fontWeight: 500 }}>
                      {'\u20AC'}{lineTotal.toFixed(2)}
                    </td>
                    <td style={{ padding: 'var(--spacing-2) var(--spacing-3)' }}>
                      <button
                        type="button"
                        className="btn btn--secondary"
                        onClick={() => removeLineItem(index)}
                        disabled={lineItems.length <= 1}
                        style={{ padding: 'var(--spacing-1) var(--spacing-2)', fontSize: '0.85rem' }}
                        title="Position entfernen"
                      >
                        ✕
                      </button>
                    </td>
                  </tr>
                )
              })}
            </tbody>
          </table>
        </div>

        <button
          type="button"
          className="btn btn--secondary"
          onClick={addLineItem}
          style={{ marginBottom: 'var(--spacing-6)' }}
        >
          + Position hinzufügen
        </button>

        <div style={{
          display: 'flex',
          justifyContent: 'flex-end',
          marginBottom: 'var(--spacing-6)',
        }}>
          <div style={{
            minWidth: '280px',
            background: 'var(--color-surface)',
            borderRadius: 'var(--radius-md)',
            padding: 'var(--spacing-4)',
            border: '1px solid var(--color-border)',
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 'var(--spacing-2)' }}>
              <span>Zwischensumme</span>
              <span>{'\u20AC'}{subtotal.toFixed(2)}</span>
            </div>
            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 'var(--spacing-2)' }}>
              <span>MwSt.</span>
              <span>{'\u20AC'}{taxTotal.toFixed(2)}</span>
            </div>
            <div style={{
              display: 'flex',
              justifyContent: 'space-between',
              fontWeight: 700,
              fontSize: '1.1rem',
              borderTop: '2px solid var(--color-border)',
              paddingTop: 'var(--spacing-2)',
            }}>
              <span>Gesamt</span>
              <span>{'\u20AC'}{total.toFixed(2)}</span>
            </div>
          </div>
        </div>

        <div className="form-section__footer">
          <button
            type="button"
            className="btn btn--secondary"
            onClick={() => navigate(-1)}
          >
            Abbrechen
          </button>
          <button
            type="submit"
            className="btn btn--primary"
            disabled={isPending}
          >
            {isPending
              ? 'Wird gespeichert...'
              : isEditing
              ? 'Änderungen speichern'
              : 'Rechnung erstellen'}
          </button>
        </div>
      </form>
    </div>
  )
}

export default InvoiceFormPage
