apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 15s

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: false
    editable: true
    jsonData:
      maxLines: 1000
      timeout: 60

  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: rentflow
    user: rentflow
    secureJsonData:
      password: rentflow_dev
    isDefault: false
    editable: true
    jsonData:
      sslmode: 'disable'
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
