################################################################################
# Traefik Static Configuration
################################################################################

global:
  checkNewVersion: false
  sendAnonymousUsage: false

log:
  level: INFO
  format: json

accessLog:
  format: json

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"

providers:
  docker:
    endpoint: unix:///var/run/docker.sock
    exposedByDefault: false
    network: rentflow_rentflow

  file:
    directory: /etc/traefik/dynamic
    watch: true
