-- QR-Login tokens for Scanner-App authentication.
-- A one-time token is generated by an admin in the web frontend,
-- encoded into a QR code, scanned by the device, and exchanged for JWTs.

CREATE TABLE IF NOT EXISTS qr_login_tokens (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    tenant_id UUID NOT NULL REFERENCES tenants(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    token VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_qr_login_tokens_token ON qr_login_tokens(token);
CREATE INDEX IF NOT EXISTS idx_qr_login_tokens_expires_at ON qr_login_tokens(expires_at);
